import { Button } from "@heroui/react";
import { Link } from "@heroui/react";
import { getTranslations } from "next-intl/server";

export const HeroContent = async () => {
  const t = await getTranslations();

  return (
    <div className="space-y-8">
      <div className="inline-block px-4 py-2 bg-orange-100 dark:bg-orange-900/30 text-orange-800 dark:text-orange-200 rounded-full text-sm font-medium">
        🚧 Prototype - Full implementation coming after dashboard completion
      </div>
      <div className="inline-block px-4 py-2 bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-200 rounded-full text-sm font-medium ml-2">
        🤖 Most content generated by AI for demonstration purposes
      </div>
      <div className="space-y-4">
        <h1 className="text-4xl lg:text-6xl font-bold text-foreground leading-tight">
          {t("hero.title")}
        </h1>
        <p className="text-xl text-default-600 leading-relaxed">
          {t("hero.subtitle")}
        </p>
      </div>
      <div className="flex flex-col sm:flex-row gap-4">
        <a href="http://localhost:3000/register" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg bg-accent px-5 py-2.5 text-sm font-semibold text-accent-foreground transition hover:bg-accent-hover">
          {t("hero.cta")}
        </a>
        <a href="http://localhost:3000/login" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-accent px-5 py-2.5 text-sm font-semibold text-accent transition hover:bg-accent/10">
          {t("navigation.login")}
        </a>
      </div>
    </div>
  );
};
